import { ImageResponse } from "next/og";

export const size = { width: 180, height: 180 };
export const contentType = "image/png";

/**
 * Apple touch icon, generated by Next from the same star as app/icon.svg.
 * iOS applies its own corner mask, so the tile is a full-bleed ivory square.
 */
export default function AppleIcon() {
  const spoke = "M0 -26 C 4.2 -26 6.2 -20.5 5 -12.5 L 2.2 -2.5 L -2.2 -2.5 L -5 -12.5 C -6.2 -20.5 -4.2 -26 0 -26 Z";
  return new ImageResponse(
    (
      <div style={{ width: 180, height: 180, background: "#f9f8f3", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <svg width="150" height="150" viewBox="-32 -32 64 64">
          <g fill="#879443">
            {[0, 45, 90, 135, 180, 225, 270, 315].map((deg) => (
              <path key={deg} d={spoke} transform={`rotate(${deg})`} />
            ))}
            <circle r="5.5" />
          </g>
        </svg>
      </div>
    ),
    size,
  );
}
