import { generateRecipes } from "@/lib/ai/generateRecipes";
import { analyzeInspiration, reanalyzeIngredients } from "@/lib/ai/analyzeInspiration";
import { generateFoodPhoto, generateIngredientArt, generateStepStill, ingredientArtPrompt } from "@/lib/ai/images";
import { downloadStepClip, pollStepClip, startStepClip, type ClipSeconds } from "@/lib/ai/video";
import type { GenerationMode } from "@/lib/ai/context";
import { config } from "@/lib/config";
import * as db from "@/lib/db";
import type { GeneratedRecipe, RecipeImage, StepMediaKind, Task } from "@/lib/types";
import { gatherContext } from "./gather";

/**
 * One handler per task type. Handlers are idempotent where it matters:
 * re-running a render task overwrites the same storage path, and
 * generate_recipes refuses to run twice for the same run.
 */

type Handler = (task: Task) => Promise<void>;

const IMAGE_KINDS: RecipeImage["kind"][] = ["hero", "angle", "plated"];

const generate_recipes: Handler = async (task) => {
  const runId = String(task.payload.run_id);
  const run = await db.getRun(runId);
  if (!run) throw new Error(`run ${runId} not found`);
  if (run.status !== "queued") return; // already generated by an earlier attempt

  await db.updateRun(runId, { status: "generating", started_at: new Date().toISOString() });
  try {
    const [settings, context] = await Promise.all([db.getSettings(), gatherContext()]);
    const mode = await resolveMode(run);
    const count = run.requested_count;
    const result = await generateRecipes({ context, mode, count, imagesPerRecipe: settings.images_per_recipe });

    await storeBatch(run, result.recipes, settings, {
      prompt: result.prompt,
      review: result.review,
      usage: result.usage,
      model: config.anthropicModel,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await db.updateRun(runId, { status: "failed", error: message, finished_at: new Date().toISOString() });
    throw err;
  }
};

const render_recipe_image: Handler = async (task) => {
  const imageId = String(task.payload.image_id);
  const recipeId = String(task.payload.recipe_id);
  const prompt = String(task.payload.prompt);
  try {
    const image = await generateFoodPhoto(prompt);
    const path = await db.uploadBytes(config.buckets.recipeImages, `recipes/${recipeId}/${imageId}.webp`, image.bytes, image.contentType);
    await db.markRecipeImage(imageId, { storage_path: path, status: "done", error: null });
  } catch (err) {
    if (task.attempts >= task.max_attempts) {
      await db.markRecipeImage(imageId, { status: "failed", error: err instanceof Error ? err.message : String(err) });
    }
    throw err;
  }
};

const render_ingredient_art: Handler = async (task) => {
  const key = String(task.payload.ingredient_key);
  const displayName = String(task.payload.display_name ?? key);
  try {
    const image = await generateIngredientArt(displayName);
    const path = await db.uploadBytes(config.buckets.ingredientArt, `ingredients/${key}.webp`, image.bytes, image.contentType);
    await db.markIngredientArt(key, { storage_path: path, status: "done", error: null });
  } catch (err) {
    if (task.attempts >= task.max_attempts) {
      await db.markIngredientArt(key, { status: "failed", error: err instanceof Error ? err.message : String(err) });
    }
    throw err;
  }
};

const analyze_inspiration: Handler = async (task) => {
  const id = String(task.payload.inspiration_id);
  const inspiration = await db.getInspiration(id);
  if (!inspiration) throw new Error(`inspiration ${id} not found`);
  await db.setInspirationAnalysis(id, { analysis_status: "running", analysis_error: null });
  try {
    const photo = inspiration.photo_path ? await db.downloadPhoto(inspiration.photo_path) : null;
    const analysis = await analyzeInspiration(inspiration, photo);
    await db.setInspirationAnalysis(id, { analysis, analysis_status: "done", analysis_error: null });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (task.attempts >= task.max_attempts) {
      await db.setInspirationAnalysis(id, { analysis_status: "failed", analysis_error: message });
    }
    throw err;
  }
};

const reanalyze_ingredients: Handler = async (task) => {
  const id = String(task.payload.inspiration_id);
  const inspiration = await db.getInspiration(id);
  if (!inspiration) throw new Error(`inspiration ${id} not found`);
  await db.setInspirationAnalysis(id, { analysis_status: "running", analysis_error: null });
  try {
    const analysis = await reanalyzeIngredients(inspiration);
    await db.setInspirationAnalysis(id, { analysis, analysis_status: "done", analysis_error: null });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (task.attempts >= task.max_attempts) {
      await db.setInspirationAnalysis(id, { analysis_status: "failed", analysis_error: message });
    }
    throw err;
  }
};
const render_step_image: Handler = async (task) => {
  const mediaId = String(task.payload.media_id);
  const media = await db.getStepMedia(mediaId);
  if (!media) return; // the recipe or the row is gone; nothing to render
  try {
    const image = await generateStepStill(media.prompt);
    const path = await db.uploadBytes(config.buckets.recipeImages, `steps/${media.recipe_id}/${media.step_number}.webp`, image.bytes, image.contentType);
    await db.markStepMedia(mediaId, { storage_path: path, status: "done", error: null });
  } catch (err) {
    if (task.attempts >= task.max_attempts) {
      await db.markStepMedia(mediaId, { status: "failed", error: err instanceof Error ? err.message : String(err) });
    }
    throw err;
  }
};

/** How long one worker slice waits on a clip before handing the job to the next slice. */
const CLIP_WAIT_MS = 150_000;
const CLIP_POLL_MS = 10_000;

/**
 * Video jobs are asynchronous on the provider side and routinely take
 * longer than a worker slice. The first attempt starts the job and stores
 * its id; every attempt polls it. If the clip is still rendering when the
 * wait budget runs out, the handler re-enqueues itself and returns success,
 * so the attempt counter is only spent on real failures.
 */
const render_step_video: Handler = async (task) => {
  const mediaId = String(task.payload.media_id);
  const media = await db.getStepMedia(mediaId);
  if (!media) return;
  try {
    let jobId = media.provider_job_id;
    if (!jobId) {
      const job = await startStepClip(media.prompt, (media.seconds ?? 8) as ClipSeconds);
      jobId = job.id;
      await db.markStepMedia(mediaId, { provider_job_id: jobId });
    }
    const deadline = Date.now() + CLIP_WAIT_MS;
    for (;;) {
      const job = await pollStepClip(jobId);
      if (job.status === "failed") throw new Error(job.error ?? "video job failed");
      if (job.status === "completed") {
        const assets = await downloadStepClip(jobId);
        const base = `steps/${media.recipe_id}/${media.step_number}`;
        const path = await db.uploadBytes(config.buckets.recipeImages, `${base}.mp4`, assets.video, "video/mp4");
        const posterPath = assets.poster
          ? await db.uploadBytes(config.buckets.recipeImages, `${base}-poster.webp`, assets.poster.bytes, assets.poster.contentType)
          : null;
        await db.markStepMedia(mediaId, { storage_path: path, poster_path: posterPath, status: "done", error: null });
        return;
      }
      if (Date.now() >= deadline) {
        await db.enqueueTask("render_step_video", { media_id: mediaId, recipe_id: media.recipe_id });
        return;
      }
      await new Promise((r) => setTimeout(r, CLIP_POLL_MS));
    }
  } catch (err) {
    if (task.attempts >= task.max_attempts) {
      await db.markStepMedia(mediaId, { status: "failed", error: err instanceof Error ? err.message : String(err) });
    }
    throw err;
  }
};

/**
 * Register pending media rows for a set of step prompts and queue one
 * render task each. Shared by the detail-page action (deterministic
 * storyboard) and the import route (agent-written prompts).
 */
export async function queueStepMedia(
  recipeId: string,
  kind: StepMediaKind,
  frames: Array<{ step_number: number; prompt: string }>,
  seconds: ClipSeconds,
) {
  const model = kind === "video" ? config.openaiVideoModel : config.openaiImageModel;
  const rows = await db.upsertStepMedia(
    frames.map((f) => ({ recipe_id: recipeId, step_number: f.step_number, kind, prompt: f.prompt, model, seconds: kind === "video" ? seconds : null })),
  );
  await db.enqueueTasks(
    rows.map((m) => ({ type: kind === "video" ? ("render_step_video" as const) : ("render_step_image" as const), payload: { media_id: m.id, recipe_id: recipeId } })),
  );
  return rows;
}

const cleanup_candidates: Handler = async () => {
  const stale = await db.listRecipeCards({ status: "candidate", sort: "oldest", limit: 100 });
  const cutoff = Date.now() - 24 * 60 * 60 * 1000;
  const ids = stale.filter((r) => new Date(r.created_at).getTime() < cutoff).map((r) => r.id);
  await db.deleteRecipes(ids);
};


/**
 * Persist a validated batch for a run: recipes (drafts for generator runs,
 * saved otherwise), image rows and render tasks, ingredient-art
 * registration, and the run's status and snapshot. Shared by the model
 * path and the import endpoint, so both produce identical results.
 */
export async function storeBatch(
  run: NonNullable<Awaited<ReturnType<typeof db.getRun>>>,
  generated: GeneratedRecipe[],
  settings: Awaited<ReturnType<typeof db.getSettings>>,
  snapshot: Record<string, unknown>,
): Promise<string[]> {
  const runId = run.id;
    const status = run.trigger === "generator" ? "candidate" : "saved";
    const recipes = await db.insertRecipes(generated, {
      run_id: runId,
      source: sourceFor(run.trigger),
      status,
      similar_to_id: run.similar_to_id,
      inspiration_id: run.inspiration_id,
    });

    // Image rows first (so the UI shows placeholders), then one task each.
    const imageRows = recipes.flatMap((r) =>
      r.image_prompts.slice(0, settings.images_per_recipe).map((prompt, position) => ({
        recipe_id: r.id,
        kind: IMAGE_KINDS[Math.min(position, IMAGE_KINDS.length - 1)],
        position,
        prompt,
      })),
    );
    const images = await db.insertRecipeImages(imageRows);
    const imageTasks = images.map((img) => ({
      type: "render_recipe_image" as const,
      payload: { image_id: img.id, recipe_id: img.recipe_id, prompt: img.prompt },
      runId,
    }));

    // Ingredient art: register every key, render only the new ones.
    let artTasks: Array<{ type: "render_ingredient_art"; payload: Record<string, unknown>; runId: string }> = [];
    if (settings.ingredient_art_enabled) {
      const items = recipes.flatMap((r) =>
        r.ingredients.map((i) => ({ ingredient_key: i.ingredient_key, display_name: i.name, prompt: ingredientArtPrompt(i.name) })),
      );
      const fresh = await db.registerIngredientArt(items);
      const byKey = new Map(items.map((i) => [i.ingredient_key, i]));
      artTasks = fresh.map((key) => ({
        type: "render_ingredient_art" as const,
        payload: { ingredient_key: key, display_name: byKey.get(key)?.display_name ?? key },
        runId,
      }));
    }

    // Two inserts on purpose: the queue is FIFO by created_at, and a single
    // insert stamps every row identically. Food photos go first so a card
    // gets its hero image before the ingredient art trickles in.
    await db.enqueueTasks(imageTasks);
    await db.enqueueTasks(artTasks);
    await db.updateRun(runId, {
      status: imageTasks.length + artTasks.length > 0 ? "rendering" : "done",
      finished_at: imageTasks.length + artTasks.length > 0 ? null : new Date().toISOString(),
      context_snapshot: { ...snapshot, recipes: recipes.map((r) => ({ id: r.id, title: r.title })) },
    });
    return recipes.map((r) => r.id);
}

export const HANDLERS: Record<Task["type"], Handler> = {
  generate_recipes,
  render_recipe_image,
  render_ingredient_art,
  analyze_inspiration,
  reanalyze_ingredients,
  cleanup_candidates,
  render_step_image,
  render_step_video,
};

/**
 * A run is done when all of its tasks have settled. The worker calls this
 * after it has marked a task done or failed (never from inside a handler,
 * whose own task row is still "running" at that point). Failed renders do
 * not fail the run: the recipe text is still useful without one image.
 */
export async function settleRunIfDone(runId: string): Promise<void> {
  const { settled } = await db.runTasksSettled(runId);
  if (!settled) return;
  const run = await db.getRun(runId);
  if (run && run.status === "rendering") {
    await db.updateRun(runId, { status: "done", finished_at: new Date().toISOString() });
  }
}

async function resolveMode(run: NonNullable<Awaited<ReturnType<typeof db.getRun>>>): Promise<GenerationMode> {
  switch (run.trigger) {
    case "scheduled": return { kind: "autonomous" };
    case "manual": return { kind: "manual" };
    case "generator": return { kind: "generator", prompt: run.prompt ?? "" };
    case "similar": {
      const recipe = run.similar_to_id ? await db.getRecipe(run.similar_to_id) : null;
      if (!recipe) throw new Error("similar run: reference recipe not found");
      return { kind: "similar", recipe, axes: run.similarity_axes ?? ["taste", "cuisine"] };
    }
    case "inspiration": {
      const inspiration = run.inspiration_id ? await db.getInspiration(run.inspiration_id) : null;
      if (!inspiration) throw new Error("inspiration run: inspiration not found");
      return { kind: "inspiration", inspiration };
    }
  }
}

function sourceFor(trigger: string): "autonomous" | "generator" | "similar" | "inspiration" {
  if (trigger === "generator") return "generator";
  if (trigger === "similar") return "similar";
  if (trigger === "inspiration") return "inspiration";
  return "autonomous";
}
